config/routes.rb
Rails.application.routes.draw do
  get 'invitations/show'

  root 'groups#new'

  resources :groups, only: [:index, :show, :new, :create]
  resources :invitations, only: :show

  #Facebook
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
end

app/models/group.rb
class Group < ActiveRecord::Base
  include Nodeable

  before_create :generate_invitation_token

  has_many :user_groups
  has_many :users, through: :user_groups

  validates :weekend_value, presence: true
  validates :talk_about_value, presence: true
  validates :meet_value, presence: true
  validates :social_status_value, presence: true

  validates :weekend_value, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10}
  validates :talk_about_value, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10}
  validates :meet_value, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10}
  validates :social_status_value, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10}

  def add_user(user)
    if valid_user? user
      self.users << user
    else
      false
    end
  end

  def coordinates
    [weekend_value, talk_about_value, meet_value, social_status_value]
  end

  def ready? 
    users.count == 3
  end

  def owner
    owner = user_groups.owner.first
    if owner
      owner.user
    else
      nil
    end
  end

  def owner=(user)
    user.user_groups.where(group: self).first.set_as_owner
  end

  private
    def valid_user?(user)
      !(users.include?(user) || users.count >= 3)
    end

    def generate_invitation_token
      self.invitation_token = UUID.new.generate
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_groups
  has_many :groups, through: :user_groups

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.name             = auth.info.name
      user.email            = auth.info.email
      user.image            = auth.info.image
      user.provider         = auth.provider
      user.uid              = auth.uid
      user.oauth_token      = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  OWNER = :owner
  
  belongs_to :user
  belongs_to :group

  scope :owner, ->{where(role: UserGroup::OWNER)}

  def set_as_owner
    self.update(role: UserGroup::OWNER)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
end

app/controllers/concerns/nodeable.rb
module Nodeable
  extend ActiveSupport::Concerns

  def distance_to(node)
    pitagoras(coordinates, node.coordinates)
  end

  def nearest
    nearest = nil
    nearest_distance = nil

    self.class.all.each do |group|
      if nearest_distance.nil?
        nearest = group
      else
        distance = group.distance_to(nearest)
        if distance < nearest_distance
          nearest = group
          nearest_distance = distance
        end
      end
    end

    nearest
  end

  private

    def pitagoras(node_a_coordinates, node_b_coordinates)
      sum   = 0
      node_a_coordinates.each_with_index do |coord, index|
        p   = coord
        q   = node_b_coordinates[index]
        sum = sum + (p - q) ** 2
      end
      Math.sqrt(sum)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
  end

  def show
    @group = Group.find params[:id]
  end

  def new
    @group = Group.new
  end

  def create
    if @group = current_user.groups.create(group_params)
      @group.owner = current_user
      redirect_to @group, flash: {success: "Group successfully Created"}
    else
      puts @group.errors.inspect
      render :new, "Group was not valid. Please try again."
    end
  end

  private
    def group_params
      params.require(:group).permit(:weekend_value, :talk_about_value, :social_status_value, :meet_value)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def show
    @group = Group.find_by invitation_token: params[:id]
  end
end

app/controllers/sessions_Controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to :back
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(flash_type)
    case flash_type.to_sym
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/alerts/_container.html.erb
<section class="col-sm-6 col-sm-offset-3">
  <% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %>" role="alert">
      <button class="close" data-dismiss="alert">×</button>
      <%= message %>
    </div>
  <% end %>
</section>

app/views/groups/_group.html.haml
%li 
  %h4= group.name
  %p
    %b Leader:
    %span= group.leader.name if group.leader
  %p
    %b companion_one:
    %span= group.companion_one.name if group.companion_one
  %p
    %b companion_two:
    %span= group.companion_two.name if group.companion_two

app/views/groups/index.html.erb
<section ng-controller="GroupsController as groups">
  <h1>{{groups.group.name}}</h1>
</section>

app/views/groups/index.html.haml
.container
  .row
    %h1 Groups
    %ul 
      =render @groups

app/views/groups/new.html.erb
<section class="col-sm-6 col-sm-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Create Group (Step 1 of 3)</h3>
    </div>
    <div class="panel-body">
      <div class="description">
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta maxime vero porro voluptatibus qui ullam iste doloremque minus quae eius iusto omnis quaerat saepe ratione, labore sequi voluptates recusandae, incidunt.
        </p>
      </div>
      <div class="slider">
        <p>
          <label for="amount">Tus fines de semana son de:</label>
          <input type="text" id="weekend-value" readonly style="border:0; color:#f6931f; font-weight:bold;">
        </p>
        <div id="slider-weekend-value"></div>
      </div>
      <div class="slider">
        <p>
          <label for="amount">Tus conversaciones son de:</label>
          <input type="text" id="talk-about-value" readonly style="border:0; color:#f6931f; font-weight:bold;">
        </p>
        <div id="slider-talk-about-value"></div>
      </div>
      <div class="slider">
        <p>
          <label for="amount">Te importa el status Social:</label>
          <input type="text" id="social-status-value" readonly style="border:0; color:#f6931f; font-weight:bold;">
        </p>
        <div id="slider-social-status-value"></div>
      </div>
      <div class="slider">
        <p>
          <label for="amount">Buscas:</label>
          <input type="text" id="meet-value" readonly style="border:0; color:#f6931f; font-weight:bold;">
        </p>
        <div id="slider-meet-value"></div>
      </div>
      <div id="user_nav">
        <% if current_user %>
          <div class="form">
            <%= form_for @group do |f|%>
              <%= f.hidden_field :weekend_value%>
              <%= f.hidden_field :talk_about_value%>
              <%= f.hidden_field :social_status_value%>
              <%= f.hidden_field :meet_value%>
              <%= f.submit "Create Group", class: "btn btn-primary btn-block" %>
            <% end %>
          </div>
          <%= link_to "Sign out", signout_path, id: "sign_out" %>
        <% else %>
          <%= link_to "Sign in with Facebook to Create Group", "/auth/facebook", id: "sign_in", class: "btn btn-primary btn-block"  %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/groups/new.html.haml
.container
  .row
    %h1 New Group
    =form_for @group do |f|
      =f.label "Name your Group"
      =f.text_field :name

  .row
    %h1 Members
    .user
      %p 
        %b Leader:
        %span=@group.leader.name if @group.leader
    .user
      %p 
        %b Companion one:
        %span=@group.companion_one.name if @group.companion_one
    .user
      %p 
        %b Companion two:
        %span=@group.companion_two.name if @group.companion_two

app/views/groups/show.html.erb
<section class="groups col-sm-6 col-sm-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Group (Step 2 of 3)</h3>
    </div>
    <div class="panel-body">
      <div class="description">
        <p>
          Comparte el link con tus amigos que quieres te acompañen. Cuando tus dos amigos se unan empezaremos con la busqueda de otro grupo de amigos.
        </p>
        <div class="link">
          <%= link_to invitation_url(id: @group.invitation_token), invitation_url(id: @group.invitation_token)%>
        </div>
      </div>
      <hr>
      <div class="members">
        <div class="member">
          <div class="media">
            <div class="media-left">
              <%=image_tag @group.owner.image%>
            </div>
            <div class="media-body media-middle">
              <h4 class="media-heading">Andres Yepes</h4>
              <p>Organizador</p>
            </div>
          </div>
        </div>
      </div>
      <div class="members">
        <div class="member">
          <div class="media">
            <a class="media-left" href="#">
              <%=image_tag "users/profile.jpeg"%>
            </a>
            <div class="media-body media-middle">
              <h4 class="media-heading">Esperando amigo 1</h4>
              Comparte el link con tus amigos para que se unan.
            </div>
          </div>
        </div>
      </div>
      <div class="members">
        <div class="member">
          <div class="media">
            <a class="media-left" href="#">
              <%=image_tag "users/profile.jpeg"%>
            </a>
            <div class="media-body media-middle">
              <h4 class="media-heading">Esperando Amigo 2</h4>
              Comparte el link con tus amigos para que se unan.
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/invitations/show.html.erb
<h1>Invitations#show</h1>
<p>Find me in app/views/invitations/show.html.erb</p>

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.pull-right
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
#user_nav
  - if current_user
    %li
      .navbar-brand 
        Signed in as
        %strong= current_user.name
        !
      = link_to "Sign out", signout_path, id: "sign_out", class: "navbar-brand"
  - else
    %li 
      = link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in", class: "navbar-brand"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="matcher">
  <head>
    <title>Matcher</title>
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= render "alerts/container", flash: flash%>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Matcher'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Matcher'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield